### ISSUE TITLE
how you fed the slides into the network?

### ISSUE THREAD

**Issue by krishnakatyal** [alvarillo89/Glands-detection#2]
what was the extension of your slides?

**Comment by alvarillo89** [comment]
Each WSI image is subsampled with a factor of 8 using QuPath software. Each subsampled image is then divided into 32x32 pixel square patches with an overlap of 16px. The network assigns a label to each of those patches.

**Comment by alvarillo89** [comment]
The original WSI images have a TIFF extension. After the subsample they are stored as PNG to simplify the processing.

**Comment by krishnakatyal** [comment]
thanks for replying i am working on .scn extension i have to work on quantification of certain cells will unet work?

**Comment by krishnakatyal** [comment]
> Each WSI image is subsampled with a factor of 8 using QuPath software. Each subsampled image is then divided into 32x32 pixel square patches with an overlap of 16px. The network assigns a label to each of those patches.
how should i do subsampling , I'm  beginner in this field

**Comment by alvarillo89** [comment]
Sorry for the delay. I did subsampling using [QuPath](https://qupath.github.io/) software, take a look at it. Maybe it is useful to subsample the images.

**Comment by krishnakatyal** [comment]
can i use u net after subsampling ?

**Comment by alvarillo89** [comment]
I don't know. I suppose you should check the minimum input size supported by U-Net. If after sub-sampling the size of your images is larger than that minimum size, then you can.
